import { Lot, EventLog, IoTTelemetry } from './types';

const AVATAR_BINH = "https://lh3.googleusercontent.com/aida-public/AB6AXuDBXdLpMI80vVrcBq-IW8Trnu5xZVBfBnxZkAvZuTmPilXHAbtzy968fDXxT6anT11UCj2X9k-CuyFZEqeoeuQaS4zqxMQp-UYRqm7FhHehIer7VhURBGSR4GFTx4FjJ1QWQ7ZoAT5LuGIPpN2INJBH0EnBL_s1zK1FXAxnHrE57H8sIIpGxwLr6DGB0hci8jd4e5m3HteowpxZGKhHgWhXJ3E-3OjXfd8SsmR8s_jieqFHpVESVbU2YOAtu5hMI6emr9wzy1SGjN4";
const AVATAR_ALPHA = "https://lh3.googleusercontent.com/aida-public/AB6AXuAnR4PaoyqaAWS7kDhr2CR_J5mu0Sr7TCA4HLDj6Vuwf2Nv9LFg_uWW7t6HPoeRQrwHiAPt_bl40dOwYPZRNLpSDMSokQ6Jz89nIzkDvkQ5e92hm8pGAzS1IrUhqMg_7OSRmhSgv1LmcOTbQCZfAdKY6GOVFaQJOXrLTRMy6Iu2KreUGD3TEjFPoyJnyH_ZdbfRwyFcoTrdXqJsfA7OGw5WGc-PFjePCZDQRrd2EW52Or9RfP7bjnsxjgqA-DSa8SatkHcsJC-2BlY";

export const INITIAL_LOTS: Lot[] = [
  {
    id: "LD-2026-0427",
    variety: "Yellow Honey Robusta",
    stage: "Processing - Honey",
    moisture: "11.2%",
    density: "720g/L",
    ph: "4.2",
    bagCount: 42,
    origin: "Dak Lak, Vietnam",
    coordinates: "12.6667° N, 108.0500° E",
    altitude: "950m Altitude",
    grower: "Mr. Nguyen Van Binh",
    growerTitle: "Primary Grower",
    growerAvatar: AVATAR_BINH,
    cuppingScore: 84,
    carbonFootprint: "2.45 kg",
    waterIntensity: "180 L",
    waterReuseEfficiency: "78%",
    eudrStatus: "Compliant",
    policyId: "8b27f67dbeaa8def9241b2e9cc88a1e3bc76fca3",
    assetName: "Lot_LD_2026_0427",
    merkleRoot: "0x4e5a32b1f7a83d290faef9a3cd29ffec3a8b8c1d",
    epoch: 482,
    altitudeNum: 950,
    description: "Managed by Mr. Nguyen Van Binh, this lot utilizes rigorous honey-processing method. Pulped selectively at premium sugar density and dried on raised beds with natural mucilage strictly controlled.",
    timeline: [
      { date: "Oct 12, 2025", title: "Growing", desc: "Monitored via IoT soil moisture network (Teros 12) with soil and nutrition balancing.", status: "completed" },
      { date: "Feb 12, 2026", title: "Harvested", desc: "Selectively hand-picked at peak ripeness (Brix 22% verified on-site).", status: "completed" },
      { date: "Feb 15, 2026", title: "Fermenting", desc: "Secured anaerobic fermentation for 36 hours tracking temperature and micro-life indicators.", status: "completed" },
      { date: "Mar 04, 2026", title: "Drying", desc: "Sun-dried in specialized greenhouse on raised beds with intact honey layer.", status: "completed" },
      { date: "In Progress", title: "Resting", desc: "Resting in parchment paper under humidity-controlled storage for flavor maturation.", status: "active" },
      { date: "Est Apr 2026", title: "Ready", desc: "Quality inspection and final export ledger validation pending.", status: "pending" }
    ]
  },
  {
    id: "VVC-2023-LAMDONG-084",
    variety: "Specialty Bourbon Arabica",
    stage: "Completed - Exported",
    moisture: "11.2%",
    density: "740g/L",
    ph: "4.5",
    bagCount: 50,
    origin: "Lâm Đồng Province, Central Highlands",
    coordinates: "11°56'44.2\"N 108°26'20.5\"E",
    altitude: "900m Altitude",
    grower: "Mr. Nguyen Van Binh",
    growerTitle: "Primary Grower",
    growerAvatar: AVATAR_BINH,
    cuppingScore: 84,
    carbonFootprint: "2.4kg CO2/kg",
    waterIntensity: "195 L",
    waterReuseEfficiency: "78%",
    eudrStatus: "Compliant",
    policyId: "8a1e5dfbbdc23e9afb948cf2ea31b3e9a4f4c392",
    assetName: "CoffeeLot_2023_84",
    merkleRoot: "0xf7a8c3de14f5bdefa9c3b7a8dcb2eef817c98e2a",
    epoch: 410,
    altitudeNum: 900,
    description: "Managed by Mr. Nguyen Van Binh, this farm specializes in high-altitude Robusta and Arabica. Utilizing regenerative agricultural practices, the farm focuses on biodiversity and natural soil health.",
    timeline: [
      { date: "September 12, 2023", title: "Sustainable Harvest", desc: "Selectively hand-picked at peak ripeness (Brix 22%).", status: "completed" },
      { date: "September 14, 2023", title: "Honey Processing", desc: "Pulped and sun-dried on raised beds with mucilage intact.", status: "completed" },
      { date: "October 05, 2023", title: "Milling & Export QC", desc: "Dry milled at Phuc Sinh facility, Da Nang.", status: "completed" }
    ]
  },
  {
    id: "LD-2026-0428",
    variety: "Conillon Robusta Alpha",
    stage: "Fermentation",
    moisture: "12.0%",
    density: "710g/L",
    ph: "4.1",
    bagCount: 35,
    origin: "Bảo Lộc, Lâm Đồng, Vietnam",
    coordinates: "11.6022° N, 107.8025° E",
    altitude: "850m Altitude",
    grower: "Mr. Pham Thanh Alpha",
    growerTitle: "Grower Operator",
    growerAvatar: AVATAR_ALPHA,
    cuppingScore: 82,
    carbonFootprint: "2.50 kg",
    waterIntensity: "210 L",
    waterReuseEfficiency: "72%",
    eudrStatus: "Compliant",
    policyId: "8b27f67dbeaa8def9241b2e9cc88a1e3bc76f452",
    assetName: "Lot_LD_2026_0428",
    merkleRoot: "0x1d3a4ef5b7a83dcf7a2ef98c91d8ceef3a8f671c",
    epoch: 482,
    altitudeNum: 850,
    description: "Located in the humid valley slopes of Bảo Lộc, this plot produces exceptionally dense Robusta beans with notes of dark cacao and spices.",
    timeline: [
      { date: "Oct 15, 2025", title: "Growing", desc: "Fed with organic compost husk mixtures and monitored for moisture levels.", status: "completed" },
      { date: "Feb 14, 2026", title: "Harvested", desc: "Gently strip-picked with manual classification to enforce sugar-rich cherries.", status: "completed" },
      { date: "In Progress", title: "Fermenting", desc: "Undergoing specialized honey-yeast inoculations for complex acidity balance.", status: "active" },
      { date: "Est Mar 2026", title: "Drying", desc: "Slated for slow natural drying cycle.", status: "pending" }
    ]
  },
  {
    id: "LD-2026-0429",
    variety: "Catimor Arabica Premier",
    stage: "Drying",
    moisture: "13.4%",
    density: "732g/L",
    ph: "4.8",
    bagCount: 60,
    origin: "Đạ Sar, Lâm Đồng, Vietnam",
    coordinates: "11.9868° N, 108.4905° E",
    altitude: "1450m Altitude",
    grower: "Mr. K'Trung",
    growerTitle: "Sourcing Partner",
    growerAvatar: AVATAR_ALPHA,
    cuppingScore: 86,
    carbonFootprint: "2.20 kg",
    waterIntensity: "140 L",
    waterReuseEfficiency: "85%",
    eudrStatus: "Compliant",
    policyId: "8b27f67dbeaa8def9241b2e9cc88a1e3bc76f592",
    assetName: "Lot_LD_2026_0429",
    merkleRoot: "0x1b7cf83a2e9aeec32fb7a8dcb2eef817c98e2a4f5b",
    epoch: 482,
    altitudeNum: 1450,
    description: "Sourced from high-altitude highlands exceeding 1400m, this Catimor lot yields premium bright cup acidity, lemon zest aroma, and medium bodies.",
    timeline: [
      { date: "Sep 20, 2025", title: "Growing", desc: "Grown in shaded forest canopy conditions protecting biological diversity.", status: "completed" },
      { date: "Jan 10, 2026", title: "Harvested", desc: "Checked Brix values of 24% before hand picking.", status: "completed" },
      { date: "Jan 12, 2026", title: "Fermenting", desc: "Washed process standard 18 hours soaking.", status: "completed" },
      { date: "In Progress", title: "Drying", desc: "Shed drying on raised screens keeping airflow robust and UV monitored.", status: "active" },
      { date: "Est May 2026", title: "Ready", desc: "Shipment packing scheduled for May final batching.", status: "pending" }
    ]
  },
  {
    id: "LD-2026-0430",
    variety: "Golden Robusta Select",
    stage: "Sorting",
    moisture: "11.8%",
    density: "715g/L",
    ph: "4.3",
    bagCount: 38,
    origin: "Gia Lai Province, Central Highlands",
    coordinates: "13.9833° N, 108.0000° E",
    altitude: "750m Altitude",
    grower: "Mrs. Tran Thi Kim",
    growerTitle: "Local Sourcing Lead",
    growerAvatar: AVATAR_ALPHA,
    cuppingScore: 81,
    carbonFootprint: "2.62 kg",
    waterIntensity: "240 L",
    waterReuseEfficiency: "70%",
    eudrStatus: "Compliant",
    policyId: "8b27f67dbeaa8def9241b2e9cc88a1e3bc76f512",
    assetName: "Lot_LD_2026_0430",
    merkleRoot: "0x8faee2a4f5b7cf83a2e9a1b7cd2eef817c98edf91c",
    epoch: 482,
    altitudeNum: 750,
    description: "Sourced from sustainable plots in Gia Lai, optimized using water-smart sprinkler systems and organic nitrogen-fixing crops.",
    timeline: [
      { date: "Nov 02, 2025", title: "Growing", desc: "Irrigation cycles guided by real-time micro-climate sensors.", status: "completed" },
      { date: "Mar 01, 2026", title: "Harvested", desc: "Fully ripe cherry harvesting.", status: "completed" },
      { date: "Mar 03, 2026", title: "Fermenting", desc: "Natural dry fermentation method.", status: "completed" },
      { date: "Mar 10, 2026", title: "Drying", desc: "Yard drying under solar monitoring arrays.", status: "completed" },
      { date: "In Progress", title: "Sorting", desc: "Milling husk separation and manual density weight sorting standard.", status: "active" }
    ]
  }
];

export const INITIAL_EVENT_LOGS: EventLog[] = [
  { id: "LOG-011", timestamp: "2023-11-20 08:45", operatorId: "OPR-4421", action: "FERTILIZE", details: "50kg Bio-organic NPK (5-5-5) / Block A-1", verified: true },
  { id: "LOG-010", timestamp: "2023-11-19 16:20", operatorId: "SYS-AUTO", action: "SENSOR ALERT", details: "Soil Moisture < 25% VWC Alert triggered - Auto pump activated", verified: true },
  { id: "LOG-009", timestamp: "2023-11-19 10:12", operatorId: "OPR-4421", action: "IRRIGATION", details: "Cycle Alpha-1 (2hrs) / Block A Drip Feed Active", verified: true },
  { id: "LOG-008", timestamp: "2023-11-18 14:00", operatorId: "OPR-9902", action: "PRUNING", details: "Zone C Canopy Clean & dead wood removal", verified: true },
  { id: "LOG-007", timestamp: "2023-11-18 09:30", operatorId: "OPR-4421", action: "FERTILIZE", details: "20kg Composted Husk Mix / Block B-East Broadcasted", verified: true },
  { id: "LOG-006", timestamp: "2023-11-17 15:45", operatorId: "SYS-AUTO", action: "SENSOR ALERT", details: "Ambient Temp > 32°C / Mist sprinkler triggered for cooling", verified: true },
];

export const INITIAL_IOT_TELEMETRY: IoTTelemetry = {
  soilMoisture: 28.4,
  temperature: 24.5,
  humidity: 72,
  ecLevels: 1.4,
  parSensor: 840
};
