name = "veriviet/coffee-passport"
version = "0.1.0"
license = "Apache-2.0"
description = "CIP-68 Coffee Passport for VerifiedVietCoffee"

[repository]
user = "Huc06"
project = "VerifiedVietCoffee"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"
